create table QRCB_UPMS.SYS_DEPT
(
    DEPT_ID     INTEGER generated always  as identity
        constraint SYS_DEPT_PK
            primary key,
    NAME        VARCHAR(50),
    SORT        INTEGER      default 0                 not null,
    CREATE_TIME TIMESTAMP default CURRENT TIMESTAMP not null,
    UPDATE_TIME TIMESTAMP                          not null generated by default for each row on update as row change timestamp ,
    DEL_FLAG    CHARACTER(1) default '0'               not null,
    PARENT_ID   INTEGER,
    TENANT_ID   INTEGER
);

comment on table QRCB_UPMS.SYS_DEPT is '部门表';

comment on column QRCB_UPMS.SYS_DEPT.DEPT_ID is '部门id';

comment on column QRCB_UPMS.SYS_DEPT.NAME is '部门名称';

comment on column QRCB_UPMS.SYS_DEPT.SORT is '排序值';

comment on column QRCB_UPMS.SYS_DEPT.CREATE_TIME is '创建时间';

comment on column QRCB_UPMS.SYS_DEPT.UPDATE_TIME is '修改时间';

comment on column QRCB_UPMS.SYS_DEPT.DEL_FLAG is '删除标记:1=已删除,0=正常';

comment on column QRCB_UPMS.SYS_DEPT.PARENT_ID is '父类ID';

comment on column QRCB_UPMS.SYS_DEPT.TENANT_ID is '租户ID';


create table QRCB_UPMS.SYS_DEPT_RELATION
(
    ANCESTOR   INTEGER not null,
    DESCENDANT INTEGER not null,
    constraint SYS_DEPT_RELATION_PK
        primary key (ANCESTOR, DESCENDANT)
);

comment on table QRCB_UPMS.SYS_DEPT_RELATION is '部门关系表';

comment on column QRCB_UPMS.SYS_DEPT_RELATION.ANCESTOR is '祖先节点';

comment on column QRCB_UPMS.SYS_DEPT_RELATION.DESCENDANT is '后代节点';

create index QRCB_UPMS.SYS_DEPT_RELATION_IDX_ANCESTOR
    on QRCB_UPMS.SYS_DEPT_RELATION (ANCESTOR);

create index QRCB_UPMS.SYS_DEPT_RELATION_IDX_DESCENDANT
    on QRCB_UPMS.SYS_DEPT_RELATION (DESCENDANT);




create table QRCB_UPMS.SYS_DICT
(
    ID          INTEGER generated always as identity
        constraint SYS_DICT_PK
            primary key,
    TYPE        VARCHAR(100),
    DESCRIPTION VARCHAR(100),
    CREATE_TIME TIMESTAMP(6) default CURRENT TIMESTAMP not null,
    UPDATE_TIME TIMESTAMP(6)                           not null generated by default for each row on update as row change timestamp ,
    REMARKS     VARCHAR(255),
    SYSTEM      CHARACTER(1) default '0'               not null,
    DEL_FLAG    CHARACTER(1) default '0'               not null,
    TENANT_ID   INTEGER      default 0                 not null
);

comment on table QRCB_UPMS.SYS_DICT is '字典表';

comment on column QRCB_UPMS.SYS_DICT.ID is '字典编号';

comment on column QRCB_UPMS.SYS_DICT.TYPE is '字典类型';

comment on column QRCB_UPMS.SYS_DICT.DESCRIPTION is '字典描述';

comment on column QRCB_UPMS.SYS_DICT.CREATE_TIME is '创建时间';

comment on column QRCB_UPMS.SYS_DICT.UPDATE_TIME is '更新时间';

comment on column QRCB_UPMS.SYS_DICT.REMARKS is '备注信息';

comment on column QRCB_UPMS.SYS_DICT.SYSTEM is '是否系统内置';

comment on column QRCB_UPMS.SYS_DICT.DEL_FLAG is '删除标记:1=已删除,0=正常';

comment on column QRCB_UPMS.SYS_DICT.TENANT_ID is '租户';

create index QRCB_UPMS.SYS_DICT_IDX_DEL_FLAG
    on QRCB_UPMS.SYS_DICT (DEL_FLAG);

create table QRCB_UPMS.SYS_DICT_ITEM
(
    ID          INTEGER     generated always as identity
        constraint SYS_DICT_ITEM_PK
            primary key,
    DICT_ID     INTEGER                                not null,
    VALUE       VARCHAR(100),
    LABEL       VARCHAR(100),
    TYPE        VARCHAR(100),
    DESCRIPTION VARCHAR(100),
    SORT        INTEGER      default 0                 not null,
    CREATE_TIME TIMESTAMP(6) default CURRENT TIMESTAMP not null,
    UPDATE_TIME TIMESTAMP(6)                           not null generated by default for each row on update as row change timestamp ,
    REMARKS     VARCHAR(255),
    DEL_FLAG    CHARACTER(1) default '0'               not null,
    TENANT_ID   INTEGER      default 0                 not null
);

comment on table QRCB_UPMS.SYS_DICT_ITEM is '字典项表';

comment on column QRCB_UPMS.SYS_DICT_ITEM.ID is '字典项id';

comment on column QRCB_UPMS.SYS_DICT_ITEM.DICT_ID is '所属字典类id';

comment on column QRCB_UPMS.SYS_DICT_ITEM.VALUE is '数据值';

comment on column QRCB_UPMS.SYS_DICT_ITEM.LABEL is '标签名';

comment on column QRCB_UPMS.SYS_DICT_ITEM.TYPE is '类型';

comment on column QRCB_UPMS.SYS_DICT_ITEM.DESCRIPTION is '描述';

comment on column QRCB_UPMS.SYS_DICT_ITEM.SORT is '排序值，默认升序';

comment on column QRCB_UPMS.SYS_DICT_ITEM.CREATE_TIME is '创建时间';

comment on column QRCB_UPMS.SYS_DICT_ITEM.UPDATE_TIME is '更新时间';

comment on column QRCB_UPMS.SYS_DICT_ITEM.REMARKS is '备注信息';

comment on column QRCB_UPMS.SYS_DICT_ITEM.DEL_FLAG is '删除标记:1=已删除,0=正常';

comment on column QRCB_UPMS.SYS_DICT_ITEM.TENANT_ID is '租户';

create index QRCB_UPMS.SYS_DICT_ITEM_IDX_DEL_FLAG
    on QRCB_UPMS.SYS_DICT_ITEM (DEL_FLAG);

create index QRCB_UPMS.SYS_DICT_ITEM_IDX_LABEL
    on QRCB_UPMS.SYS_DICT_ITEM (LABEL);

create index QRCB_UPMS.SYS_DICT_ITEM_IDX_VALUE
    on QRCB_UPMS.SYS_DICT_ITEM (VALUE);


create table QRCB_UPMS.SYS_FILE
(
    ID          BIGINT          generated always as identity
        constraint SYS_FILE_PK
            primary key,
    FILE_NAME   VARCHAR(100),
    BUCKET_NAME VARCHAR(200),
    ORIGINAL    VARCHAR(100),
    TYPE        VARCHAR(50),
    FILE_SIZE   BIGINT,
    CREATE_USER VARCHAR(32),
    CREATE_TIME TIMESTAMP(6) default CURRENT TIMESTAMP not null,
    UPDATE_USER VARCHAR(32),
    UPDATE_TIME TIMESTAMP(6)                           not null generated by default for each row on update as row change timestamp ,
    DEL_FLAG    CHARACTER(1) default '0'               not null,
    TENANT_ID   INTEGER
);

comment on table QRCB_UPMS.SYS_FILE is '文件管理表';

comment on column QRCB_UPMS.SYS_FILE.ID is '文件编号';

comment on column QRCB_UPMS.SYS_FILE.FILE_NAME is '文件名';

comment on column QRCB_UPMS.SYS_FILE.BUCKET_NAME is '存储桶名称';

comment on column QRCB_UPMS.SYS_FILE.ORIGINAL is '原始文件名';

comment on column QRCB_UPMS.SYS_FILE.TYPE is '文件类型';

comment on column QRCB_UPMS.SYS_FILE.FILE_SIZE is '文件大小';

comment on column QRCB_UPMS.SYS_FILE.CREATE_USER is '创建者';

comment on column QRCB_UPMS.SYS_FILE.CREATE_TIME is '创建时间';

comment on column QRCB_UPMS.SYS_FILE.UPDATE_USER is '更新者';

comment on column QRCB_UPMS.SYS_FILE.UPDATE_TIME is '更新时间';

comment on column QRCB_UPMS.SYS_FILE.DEL_FLAG is '删除标记:1=已删除,0=正常';

comment on column QRCB_UPMS.SYS_FILE.TENANT_ID is '租户';


create table QRCB_UPMS.SYS_LOG
(
    ID          BIGINT                 generated always as identity
        constraint SYS_LOG_PK
            primary key,
    TYPE        CHARACTER(1) default '0'               not null,
    TITLE       VARCHAR(255),
    SERVICE_ID  VARCHAR(32),
    CREATE_BY   VARCHAR(255),
    CREATE_TIME TIMESTAMP(6) default CURRENT TIMESTAMP not null,
    UPDATE_TIME TIMESTAMP(6)                           not null generated by default for each row on update as row change timestamp ,
    REMOTE_ADDR VARCHAR(255),
    USER_AGENT  VARCHAR(1000),
    REQUEST_URI VARCHAR(255),
    METHOD      VARCHAR(10),
    PARAMS      CLOB(1048576),
    TIME        BIGINT,
    DEL_FLAG    CHARACTER(1) default '0'               not null,
    EXCEPTION   CLOB(1048576),
    TENANT_ID   INTEGER      default 0                 not null
);

comment on table QRCB_UPMS.SYS_LOG is '日志表';

comment on column QRCB_UPMS.SYS_LOG.ID is '日志编号';

comment on column QRCB_UPMS.SYS_LOG.TYPE is '日志类型';

comment on column QRCB_UPMS.SYS_LOG.TITLE is '日志标题';

comment on column QRCB_UPMS.SYS_LOG.SERVICE_ID is '应用标识';

comment on column QRCB_UPMS.SYS_LOG.CREATE_BY is '创建人';

comment on column QRCB_UPMS.SYS_LOG.CREATE_TIME is '创建时间';

comment on column QRCB_UPMS.SYS_LOG.UPDATE_TIME is '更新时间';

comment on column QRCB_UPMS.SYS_LOG.REMOTE_ADDR is '操作ip地址';

comment on column QRCB_UPMS.SYS_LOG.USER_AGENT is '用户代理';

comment on column QRCB_UPMS.SYS_LOG.REQUEST_URI is '请求uri';

comment on column QRCB_UPMS.SYS_LOG.METHOD is '操作方式';

comment on column QRCB_UPMS.SYS_LOG.PARAMS is '提交数据';

comment on column QRCB_UPMS.SYS_LOG.TIME is '方法执行时间';

comment on column QRCB_UPMS.SYS_LOG.DEL_FLAG is '删除标记:1=已删除,0=正常';

comment on column QRCB_UPMS.SYS_LOG.EXCEPTION is '异常信息';

comment on column QRCB_UPMS.SYS_LOG.TENANT_ID is '租户';

create index QRCB_UPMS.SYS_LOG_IDX_CREATE_BY
    on QRCB_UPMS.SYS_LOG (CREATE_BY);

create index QRCB_UPMS.SYS_LOG_IDX_CREATE_DATETIME
    on QRCB_UPMS.SYS_LOG (CREATE_TIME);

create index QRCB_UPMS.SYS_LOG_IDX_REQUEST_URI
    on QRCB_UPMS.SYS_LOG (REQUEST_URI);

create index QRCB_UPMS.SYS_LOG_IDX_TYPE
    on QRCB_UPMS.SYS_LOG (TYPE);

create table QRCB_UPMS.SYS_MENU
(
    MENU_ID     INTEGER   not null
        constraint SYS_MENU_PK
            primary key,
    NAME        VARCHAR(32),
    PERMISSION  VARCHAR(32),
    PATH        VARCHAR(128),
    PARENT_ID   INTEGER,
    ICON        VARCHAR(32),
    SORT        INTEGER      default 1,
    KEEP_ALIVE  CHARACTER(1) default '0'               not null,
    TYPE        CHARACTER(1) default '0'               not null,
    CREATE_TIME TIMESTAMP(6) default CURRENT TIMESTAMP not null,
    UPDATE_TIME TIMESTAMP(6)                           not null generated by default for each row on update as row change timestamp ,
    DEL_FLAG    CHARACTER(1) default '0'               not null,
    TENANT_ID   INTEGER
);

comment on table QRCB_UPMS.SYS_MENU is '菜单表';

comment on column QRCB_UPMS.SYS_MENU.MENU_ID is '菜单id';

comment on column QRCB_UPMS.SYS_MENU.NAME is '菜单名称';

comment on column QRCB_UPMS.SYS_MENU.PERMISSION is '菜单权限标识';

comment on column QRCB_UPMS.SYS_MENU.PATH is '前端路由标识路径';

comment on column QRCB_UPMS.SYS_MENU.PARENT_ID is '菜单父id';

comment on column QRCB_UPMS.SYS_MENU.ICON is '菜单图标';

comment on column QRCB_UPMS.SYS_MENU.SORT is '排序值';

comment on column QRCB_UPMS.SYS_MENU.KEEP_ALIVE is '路由缓冲';

comment on column QRCB_UPMS.SYS_MENU.TYPE is '菜单类型:0=菜单,1=按钮';

comment on column QRCB_UPMS.SYS_MENU.CREATE_TIME is '创建时间';

comment on column QRCB_UPMS.SYS_MENU.UPDATE_TIME is '更新时间';

comment on column QRCB_UPMS.SYS_MENU.DEL_FLAG is '删除标记:1=已删除,0=正常';

comment on column QRCB_UPMS.SYS_MENU.TENANT_ID is '租户';

create table QRCB_UPMS.SYS_OAUTH_CLIENT_DETAILS
(
    ID                      INTEGER           generated always as identity
        constraint SYS_OAUTH_CLIENT_DETAILS_PK
            primary key,
    CLIENT_ID               VARCHAR(32)              not null,
    RESOURCE_IDS            VARCHAR(256),
    CLIENT_SECRET           VARCHAR(256),
    SCOPE                   VARCHAR(256),
    AUTHORIZED_GRANT_TYPES  VARCHAR(256),
    WEB_SERVER_REDIRECT_URI VARCHAR(256),
    AUTHORITIES             VARCHAR(256),
    ACCESS_TOKEN_VALIDITY   INTEGER,
    REFRESH_TOKEN_VALIDITY  INTEGER,
    ADDITIONAL_INFORMATION  VARCHAR(4096),
    AUTO_APPROVE            VARCHAR(256),
    DEL_FLAG                CHARACTER(1) default '0' not null,
    TENANT_ID               INTEGER      default 0   not null
);

comment on table QRCB_UPMS.SYS_OAUTH_CLIENT_DETAILS is '客户端信息表';

comment on column QRCB_UPMS.SYS_OAUTH_CLIENT_DETAILS.ID is 'id';

comment on column QRCB_UPMS.SYS_OAUTH_CLIENT_DETAILS.CLIENT_ID is '客户端id';

comment on column QRCB_UPMS.SYS_OAUTH_CLIENT_DETAILS.RESOURCE_IDS is '资源id列表';

comment on column QRCB_UPMS.SYS_OAUTH_CLIENT_DETAILS.CLIENT_SECRET is '客户端密钥';

comment on column QRCB_UPMS.SYS_OAUTH_CLIENT_DETAILS.SCOPE is '作用域';

comment on column QRCB_UPMS.SYS_OAUTH_CLIENT_DETAILS.AUTHORIZED_GRANT_TYPES is '授权方式';

comment on column QRCB_UPMS.SYS_OAUTH_CLIENT_DETAILS.WEB_SERVER_REDIRECT_URI is '回调地址';

comment on column QRCB_UPMS.SYS_OAUTH_CLIENT_DETAILS.AUTHORITIES is '权限列表';

comment on column QRCB_UPMS.SYS_OAUTH_CLIENT_DETAILS.ACCESS_TOKEN_VALIDITY is '请求令牌有效时间';

comment on column QRCB_UPMS.SYS_OAUTH_CLIENT_DETAILS.REFRESH_TOKEN_VALIDITY is '刷新令牌有效时间';

comment on column QRCB_UPMS.SYS_OAUTH_CLIENT_DETAILS.ADDITIONAL_INFORMATION is '扩展信息';

comment on column QRCB_UPMS.SYS_OAUTH_CLIENT_DETAILS.AUTO_APPROVE is '是否自动放行';

comment on column QRCB_UPMS.SYS_OAUTH_CLIENT_DETAILS.DEL_FLAG is '删除标记:1=已删除,0=正常';

comment on column QRCB_UPMS.SYS_OAUTH_CLIENT_DETAILS.TENANT_ID is '租户';


create table QRCB_UPMS.SYS_PUBLIC_PARAM
(
    PUBLIC_ID     BIGINT                    generated always as identity
        constraint SYS_PUBLIC_PARAM_PK
            primary key,
    PUBLIC_NAME   VARCHAR(128),
    PUBLIC_KEY    VARCHAR(128),
    PUBLIC_VALUE  VARCHAR(128),
    STATUS        CHARACTER(1) default '0'               not null,
    VALIDATE_CODE VARCHAR(64),
    CREATE_TIME   TIMESTAMP(6) default CURRENT TIMESTAMP not null,
    UPDATE_TIME   TIMESTAMP(6) not null generated by default for each row on update as row change timestamp ,
    PUBLIC_TYPE   CHARACTER(1) default '0'               not null,
    SYSTEM        CHARACTER(1) default '0'               not null,
    DEL_FLAG      CHARACTER(1) default '0'               not null,
    TENANT_ID     INTEGER
);

comment on table QRCB_UPMS.SYS_PUBLIC_PARAM is '公共参数表';

comment on column QRCB_UPMS.SYS_PUBLIC_PARAM.PUBLIC_ID is '公共参数编号';

comment on column QRCB_UPMS.SYS_PUBLIC_PARAM.PUBLIC_NAME is '公共参数名称';

comment on column QRCB_UPMS.SYS_PUBLIC_PARAM.PUBLIC_KEY is '键[英文大写+下划线]';

comment on column QRCB_UPMS.SYS_PUBLIC_PARAM.PUBLIC_VALUE is '值';

comment on column QRCB_UPMS.SYS_PUBLIC_PARAM.STATUS is '标识:1=有效,2=无效';

comment on column QRCB_UPMS.SYS_PUBLIC_PARAM.VALIDATE_CODE is '编码';

comment on column QRCB_UPMS.SYS_PUBLIC_PARAM.CREATE_TIME is '创建时间';

comment on column QRCB_UPMS.SYS_PUBLIC_PARAM.UPDATE_TIME is '修改时间';

comment on column QRCB_UPMS.SYS_PUBLIC_PARAM.PUBLIC_TYPE is '配置类型：0=默认,1=检索,2=原文,3=报表,4=安全,5=文档,6=消息,9=其他';

comment on column QRCB_UPMS.SYS_PUBLIC_PARAM.SYSTEM is '是否是系统内置';

comment on column QRCB_UPMS.SYS_PUBLIC_PARAM.DEL_FLAG is '状态:0=正常,1=删除';

comment on column QRCB_UPMS.SYS_PUBLIC_PARAM.TENANT_ID is '租户';


create table QRCB_UPMS.SYS_ROLE
(
    ROLE_ID     INTEGER                          generated always as identity
        constraint SYS_ROLE_PK
            primary key,
    ROLE_NAME   VARCHAR(64),
    ROLE_CODE   VARCHAR(64),
    ROLE_DESC   VARCHAR(255),
    DS_TYPE     CHARACTER(1) default '2'               not null,
    DS_SCOPE    VARCHAR(255),
    CREATE_TIME TIMESTAMP(6) default CURRENT TIMESTAMP not null,
    UPDATE_TIME TIMESTAMP(6)                           not null generated by default for each row on update as row change timestamp ,
    DEL_FLAG    CHARACTER(1) default '0'               not null,
    TENANT_ID   INTEGER
);

comment on table QRCB_UPMS.SYS_ROLE is '角色表';

comment on column QRCB_UPMS.SYS_ROLE.ROLE_ID is '角色编号';

comment on column QRCB_UPMS.SYS_ROLE.ROLE_NAME is '角色名称';

comment on column QRCB_UPMS.SYS_ROLE.ROLE_CODE is '角色标识';

comment on column QRCB_UPMS.SYS_ROLE.ROLE_DESC is '角色描述';

comment on column QRCB_UPMS.SYS_ROLE.DS_TYPE is '数据权限类型';

comment on column QRCB_UPMS.SYS_ROLE.DS_SCOPE is '数据权限作用范围';

comment on column QRCB_UPMS.SYS_ROLE.CREATE_TIME is '创建时间';

comment on column QRCB_UPMS.SYS_ROLE.UPDATE_TIME is '修改时间';

comment on column QRCB_UPMS.SYS_ROLE.DEL_FLAG is '删除标记:1=已删除,0=正常';

comment on column QRCB_UPMS.SYS_ROLE.TENANT_ID is '租户';

create index QRCB_UPMS.SYS_ROLE_IDX_ROLE_CODE
    on QRCB_UPMS.SYS_ROLE (ROLE_CODE);

create table QRCB_UPMS.SYS_ROLE_MENU
(
    ROLE_ID INTEGER not null,
    MENU_ID INTEGER not null,
    constraint SYS_ROLE_MENU_PK
        primary key (ROLE_ID, MENU_ID)
);

comment on table QRCB_UPMS.SYS_ROLE_MENU is '角色菜单表';

comment on column QRCB_UPMS.SYS_ROLE_MENU.ROLE_ID is '角色id';

comment on column QRCB_UPMS.SYS_ROLE_MENU.MENU_ID is '菜单id';

create table QRCB_UPMS.SYS_ROUTE_CONF
(
    ID          INTEGER                         generated always as identity
        constraint SYS_ROUTE_CONF_PK
            primary key,
    ROUTE_NAME  VARCHAR(30),
    ROUTE_ID    VARCHAR(30),
    PREDICATES  CLOB(1048576),
    FILTERS     CLOB(1048576),
    URI         VARCHAR(50),
    ORDER       INTEGER      default 0                 not null,
    CREATE_TIME TIMESTAMP(6) default CURRENT TIMESTAMP not null,
    UPDATE_TIME TIMESTAMP(6)                           not null generated by default for each row on update as row change timestamp ,
    DEL_FLAG    CHARACTER(1) default '0'               not null
);

comment on table QRCB_UPMS.SYS_ROUTE_CONF is '网关路由信息表';

comment on column QRCB_UPMS.SYS_ROUTE_CONF.ID is '主键';

comment on column QRCB_UPMS.SYS_ROUTE_CONF.ROUTE_NAME is '路由名称';

comment on column QRCB_UPMS.SYS_ROUTE_CONF.ROUTE_ID is '路由id';

comment on column QRCB_UPMS.SYS_ROUTE_CONF.PREDICATES is '断言';

comment on column QRCB_UPMS.SYS_ROUTE_CONF.FILTERS is '过滤器';

comment on column QRCB_UPMS.SYS_ROUTE_CONF.URI is '请求uri';

comment on column QRCB_UPMS.SYS_ROUTE_CONF.ORDER is '排序值';

comment on column QRCB_UPMS.SYS_ROUTE_CONF.CREATE_TIME is '创建时间';

comment on column QRCB_UPMS.SYS_ROUTE_CONF.UPDATE_TIME is '修改时间';

comment on column QRCB_UPMS.SYS_ROUTE_CONF.DEL_FLAG is '删除标记:1=已删除,0=正常';

create table QRCB_UPMS.SYS_SOCIAL_DETAILS
(
    ID           INTEGER                  generated always as identity
        constraint SYS_SOCIAL_DETAILS_PK
            primary key,
    TYPE         VARCHAR(16),
    REMARK       VARCHAR(64),
    APP_ID       VARCHAR(64),
    APP_SECRET   VARCHAR(64),
    REDIRECT_URL VARCHAR(128),
    CREATE_TIME  TIMESTAMP(6) default CURRENT TIMESTAMP not null,
    UPDATE_TIME  TIMESTAMP(6)                           not null generated by default for each row on update as row change timestamp ,
    DEL_FLAG     CHARACTER(1) default '0'               not null,
    TENANT_ID    INTEGER      default 0                 not null
);

comment on table QRCB_UPMS.SYS_SOCIAL_DETAILS is '第三方账号信息表';

comment on column QRCB_UPMS.SYS_SOCIAL_DETAILS.ID is '主键';

comment on column QRCB_UPMS.SYS_SOCIAL_DETAILS.TYPE is '账号类型';

comment on column QRCB_UPMS.SYS_SOCIAL_DETAILS.REMARK is '描述';

comment on column QRCB_UPMS.SYS_SOCIAL_DETAILS.APP_ID is 'appId';

comment on column QRCB_UPMS.SYS_SOCIAL_DETAILS.APP_SECRET is 'app secret';

comment on column QRCB_UPMS.SYS_SOCIAL_DETAILS.REDIRECT_URL is '回调地址';

comment on column QRCB_UPMS.SYS_SOCIAL_DETAILS.CREATE_TIME is '创建时间';

comment on column QRCB_UPMS.SYS_SOCIAL_DETAILS.UPDATE_TIME is '更新时间';

comment on column QRCB_UPMS.SYS_SOCIAL_DETAILS.DEL_FLAG is '删除标记:1=已删除,0=正常';

comment on column QRCB_UPMS.SYS_SOCIAL_DETAILS.TENANT_ID is '租户';

create table QRCB_UPMS.SYS_TENANT
(
    ID          INTEGER                   generated always as identity
        constraint SYS_TENANT_PK
            primary key,
    NAME        VARCHAR(255),
    CODE        VARCHAR(64),
    START_TIME  TIMESTAMP(6),
    END_TIME    TIMESTAMP(6),
    STATUS      CHARACTER(1) default '0'               not null,
    DEL_FLAG    CHARACTER(1) default '0'               not null,
    CREATE_TIME TIMESTAMP(6) default CURRENT TIMESTAMP not null,
    UPDATE_TIME TIMESTAMP(6)                           not null  generated by default for each row on update as row change timestamp
);

comment on table QRCB_UPMS.SYS_TENANT is '租户信息表';

comment on column QRCB_UPMS.SYS_TENANT.ID is '租户id';

comment on column QRCB_UPMS.SYS_TENANT.NAME is '租户名称';

comment on column QRCB_UPMS.SYS_TENANT.CODE is '租户编号';

comment on column QRCB_UPMS.SYS_TENANT.START_TIME is '开始时间';

comment on column QRCB_UPMS.SYS_TENANT.END_TIME is '结束时间';

comment on column QRCB_UPMS.SYS_TENANT.STATUS is '租户冻结标记:9=冻结,0=正常';

comment on column QRCB_UPMS.SYS_TENANT.DEL_FLAG is '删除标记:1=已删除,0=正常';

comment on column QRCB_UPMS.SYS_TENANT.CREATE_TIME is '创建时间';

comment on column QRCB_UPMS.SYS_TENANT.UPDATE_TIME is '更新时间';

create table QRCB_UPMS.SYS_USER
(
    USER_ID     INTEGER              generated always as identity
        constraint SYS_USER_PK
            primary key,
    USERNAME    VARCHAR(64),
    PASSWORD    VARCHAR(255),
    SALT        VARCHAR(255),
    PHONE       VARCHAR(20),
    AVATAR      VARCHAR(255),
    DEPT_ID     INTEGER,
    CREATE_TIME TIMESTAMP(6) default CURRENT TIMESTAMP not null,
    UPDATE_TIME TIMESTAMP(6)                           not null generated by default for each row on update as row change timestamp ,
    LOCK_FLAG   CHARACTER(1) default '0'               not null,
    DEL_FLAG    CHARACTER(1) default '0'               not null,
    WX_OPENID   VARCHAR(32),
    MINI_OPENID VARCHAR(32),
    QQ_OPENID   VARCHAR(32),
    GITEE_LOGIN VARCHAR(100),
    OSC_ID      VARCHAR(100),
    TENANT_ID   INTEGER      default 0                 not null
);

comment on table QRCB_UPMS.SYS_USER is '用户表';

comment on column QRCB_UPMS.SYS_USER.USER_ID is '主键id';

comment on column QRCB_UPMS.SYS_USER.USERNAME is '用户名';

comment on column QRCB_UPMS.SYS_USER.PASSWORD is '密码';

comment on column QRCB_UPMS.SYS_USER.SALT is '随机盐';

comment on column QRCB_UPMS.SYS_USER.PHONE is '手机号';

comment on column QRCB_UPMS.SYS_USER.AVATAR is '头像地址';

comment on column QRCB_UPMS.SYS_USER.DEPT_ID is '用户所属部门id';

comment on column QRCB_UPMS.SYS_USER.CREATE_TIME is '创建时间';

comment on column QRCB_UPMS.SYS_USER.UPDATE_TIME is '修改时间';

comment on column QRCB_UPMS.SYS_USER.LOCK_FLAG is '锁定标记';

comment on column QRCB_UPMS.SYS_USER.DEL_FLAG is '删除标记:1=已删除,0=正常';

comment on column QRCB_UPMS.SYS_USER.WX_OPENID is '微信openid';

comment on column QRCB_UPMS.SYS_USER.MINI_OPENID is '微信小程序openid';

comment on column QRCB_UPMS.SYS_USER.QQ_OPENID is 'QQ openid';

comment on column QRCB_UPMS.SYS_USER.GITEE_LOGIN is '码云唯一标识';

comment on column QRCB_UPMS.SYS_USER.OSC_ID is '开源中国唯一标识';

comment on column QRCB_UPMS.SYS_USER.TENANT_ID is '用户所属租户id';

create index QRCB_UPMS.SYS_USER_IDX_QQ_OPENID
    on QRCB_UPMS.SYS_USER (QQ_OPENID);

create index QRCB_UPMS.SYS_USER_IDX_USERNAME
    on QRCB_UPMS.SYS_USER (USERNAME);

create index QRCB_UPMS.SYS_USER_IDX_WX_OPENID
    on QRCB_UPMS.SYS_USER (WX_OPENID);

create table QRCB_UPMS.SYS_USER_ROLE
(
    USER_ID INTEGER not null,
    ROLE_ID INTEGER not null,
    constraint SYS_USER_ROLE_PK
        primary key (USER_ID, ROLE_ID)
);

comment on table QRCB_UPMS.SYS_USER_ROLE is '用户角色表';

comment on column QRCB_UPMS.SYS_USER_ROLE.USER_ID is '用户id';

comment on column QRCB_UPMS.SYS_USER_ROLE.ROLE_ID is '角色id';

